license/readme.md　の翻訳
Moddable-OpenSource/moddable-jp pull request #11
Opened 2024-04-24 14:23 UTC by stc1988

@meganetaaan さんレビューお願いします。

2024-04-26 04:06 UTC, meganetaaan requested changes
1点、元リポジトリ側の誤りを見つけました。

リンクのURLなど翻訳後の文書にも影響する場合は、翻訳時に修正してしまって、後から本体側にも同様の修正PRを出すのが良いかと思います。

2024-04-26 04:06 UTC, meganetaaan commented on licenses/readme.md
> +Moddable SDKに含まれるいくつかのフォントは、SIL OPEN FONT LICENSE Version 1.1ライセンスの下で提供されています。このライセンスのテキストは [OFL.txt](./OFT.txt) に提供されています。
リンクのパスがtypoです。元文書からあるミスですね。

```suggestion
Moddable SDKに含まれるいくつかのフォントは、SIL OPEN FONT LICENSE Version 1.1ライセンスの下で提供されています。このライセンスのテキストは [OFL.txt](./OFL.txt) に提供されています。
```

2024-04-26 04:06 UTC, meganetaaan commented on licenses/readme.md
> +Moddable SDKに含まれるいくつかのフォントは、SIL OPEN FONT LICENSE Version 1.1ライセンスの下で提供されています。このライセンスのテキストは [OFL.txt](./OFT.txt) に提供されています。
元リポジトリ側の修正は別扱いにして、このPRで修正してしまって良いと思います。

2024-04-26 05:03 UTC, stc1988 commented on licenses/readme.md
> +Moddable SDKに含まれるいくつかのフォントは、SIL OPEN FONT LICENSE Version 1.1ライセンスの下で提供されています。このライセンスのテキストは [OFL.txt](./OFT.txt) に提供されています。
確認ありがとうございます。
軽微な修正なので、後でPR出しておきます。

翻訳フローにも、「翻訳元に誤りを発見したら」みたいなパートを追加した方が良さそうですね。

2024-04-27 01:35 UTC, stc1988 commented
提案いただいた修正で取り込みました。
原文リンク切れ問題は調べると結構ありそうだったので、整理してまとめて対応します

2024-04-29 04:21 UTC, meganetaaan approved these changes
LGTMです🙆

2024-04-29 04:22 UTC, merged

2024-04-30 01:52 UTC, stc1988 commented
元リポジトリの修正は[PR](https://github.com/Moddable-OpenSource/moddable/pull/1338)してマージ済みです