documention/tools　の翻訳
Moddable-OpenSource/moddable-jp pull request #15
Opened 2024-05-05 02:37 UTC by stc1988

@meganetaaan 1PRのボリュームが多くなり申し訳ございませんが、レビューお願いします

2024-05-09 11:19 UTC, meganetaaan requested changes
翻訳に違和感ある点にsuggestion入れました。ご確認ください🙏

2024-05-09 11:19 UTC, meganetaaan commented on documentation/tools/manifest.md
> +`static` プロパティはマイクロコントローラにとって最も重要です。これは、スタック、オブジェクト、バイトコード、文字列など、JavaScript言語ランタイムが使用できるバイト数の合計です。ブックキーピングのオーバーヘッドを最小限に抑え、ランタイムが固定サイズのスロットと可変サイズのチャンクの領域を動的に管理できるように、単一のメモリブロックとして割り当てられます。`static` プロパ
やや翻訳に違和感があったので微修正してみました

```suggestion
`static` プロパティはマイクロコントローラにとって最も重要です。これは、スタック、オブジェクト、バイトコード、文字列など、JavaScript言語ランタイムが使用できるバイト数の合計です。ブックキーピングのオーバーヘッドを最小限に抑え、ランタイムが固定サイズのスロットと可変サイズのチャンクの領域を動的に管理できるように、単一のメモリブロックとして割り当てられます。`static` プロパティは、言語ランタイムによって割り当てられるメモリに厳格な制限を課し、スクリプトがメモリ予算を超過しないことを保証します（もし超過できると、スクリプトがホストOSに必要なメモリを取ってしまい、障害や不安定性を引き起こす可能性があります）。
```

2024-05-09 11:19 UTC, meganetaaan commented on documentation/tools/manifest.md
> +- `static` プロパティを `0` に設定して、静的アロケータを無効にします。（プロパティを削除するだけでは不十分です。`static` プロパティは含まれているマニフェストで定義されている可能性があります）
```suggestion
- `static` プロパティを `0` に設定して、静的アロケータを無効にします。（プロパティを削除するだけでは不十分です。`static` プロパティはインクルードされたマニフェストで定義されている可能性があります）
```

2024-05-09 11:19 UTC, meganetaaan commented on documentation/tools/manifest.md
> +`static` プロパティはシミュレーターによって無視されます。シミュレーターはオンデマンドでメモリ割り当てにフォールバックします。コンピュータはマイクロコントローラに比べてほぼ無限のメモリを持っているため、これは問題ではありません。
オンデマンドはフォールバックではなくメモリ割り当ての方に係る語句ですね。
```suggestion
`static` プロパティはシミュレーターでは無視されます。シミュレーターはオンデマンドのメモリ割り当てにフォールバックします。コンピュータはマイクロコントローラに比べてほぼ無限のメモリを持っているため、これは問題ではありません。
```

2024-05-09 11:19 UTC, meganetaaan commented on documentation/tools/manifest.md
> +`static` プロパティはシミュレーターによって無視されます。シミュレーターはオンデマンドでメモリ割り当てにフォールバックします。コンピュータはマイクロコントローラに比べてほぼ無限のメモリを持っているため、これは問題ではありません。
オンデマンドはフォールバックではなくメモリ割り当ての方に係る語句ですね。
```suggestion
`static` プロパティはシミュレーターでは無視されます。シミュレーターはオンデマンドのメモリ割り当てにフォールバックします。コンピュータはマイクロコントローラに比べてほぼ無限のメモリを持っているため、これは問題ではありません。
```

2024-05-09 11:19 UTC, meganetaaan commented on documentation/tools/manifest.md
> +また、各プラットフォームのファイルシステムのルートを指定するために [files manifest](../../modules/files/file/manifest.json)、いくつかのネットワーキングの例でWi-Fi認証情報を指定するためにも使用されます。
```suggestion
また、[files manifest](../../modules/files/file/manifest.json)で各プラットフォームのファイルシステムのルートを指定したり 、いくつかのネットワーキングの例でWi-Fi認証情報を指定したりするためにも使用されます。
```

2024-05-09 11:19 UTC, meganetaaan commented on documentation/tools/tools.md
> +**mcrun** は、[mods](../xs/mods.md) をビルドするコマンドラインツールです。modsは、新しい機能を追加したり、既存の挙動を変更したりするスクリプトで、ユーザーがIoT製品にインストールできます。modをビルドするための入力は、JavaScriptモジュール、アセット、データ、および設定で、これらはマニフェストで指定されます。出力は、JavaScriptバイトコード
```suggestion
**mcrun** は、[mod](../xs/mods.md) をビルドするコマンドラインツールです。modは、新しい機能を追加したり、既存の挙動を変更したりするスクリプトで、ユーザーがIoT製品にインストールできます。modをビルドするための入力は、JavaScriptモジュール、アセット、データ、および設定で、これらはマニフェストで指定されます。出力は、JavaScriptバイトコードとリソースデータを含むXSアーカイブファイル（`.xsa` 拡張子）です。
```

2024-05-09 11:19 UTC, meganetaaan commented on documentation/tools/tools.md
> +**mcrez**はリソースマップにアセットを含むコマンドラインツールです。**mcrez**はアセット自体とそれにアクセスする方法を含むCコードを生成します。
```suggestion
**mcrez**はリソースマップにアセットを含めるコマンドラインツールです。**mcrez**はアセット自体とそれにアクセスする方法を含むCコードを生成します。
```

2024-05-09 15:47 UTC, stc1988 commented
レビュありがとうございます。指摘内容について取り込みました

2024-05-14 14:54 UTC, meganetaaan approved these changes
LGTMです :+1:

2024-05-14 14:54 UTC, merged