documentation/xs/xsbug.md の翻訳
Moddable-OpenSource/moddable-jp pull request #16
Opened 2024-05-07 11:02 UTC by stc1988

@meganetaaan さんレビュお願いします

2024-05-09 11:33 UTC, meganetaaan requested changes
軽微な指摘あります🙇

2024-05-09 15:17 UTC, stc1988 commented
確認ありがとうございます。指摘のコメントはどこに記載されているでしょうか

2024-05-14 14:51 UTC, meganetaaan submitted a review, later dismissed
前回レビューコメントがうまく投稿できていませんでした :bow:
翻訳時の違和感ある表現について軽微な修正をしました。

2024-05-14 14:51 UTC, meganetaaan commented on documentation/xs/xsbug.md
> +**Network** Preferencesパネルは、**xsbug** がリスニングしているインターフェースを表示し、**xsbug** が使用しているポート番号を変更するための編集フィールドを提供します。デフォルトのポート番号は **5002** です。ポート番号を変更すると、接続されている仮想マシンは停止します。
```suggestion
**Network** Preferencesパネルは、**xsbug** がリッスンしているインターフェースを表示し、**xsbug** が使用しているポート番号を変更するための編集フィールドを提供します。デフォルトのポート番号は **5002** です。ポート番号を変更すると、接続されている仮想マシンは停止します。
```

2024-05-14 14:51 UTC, meganetaaan commented on documentation/xs/xsbug.md
> +## コンソール/ログのカラー化とトレース
```suggestion
## コンソール/ログの色付けとトレース
```

2024-05-14 14:51 UTC, meganetaaan commented on documentation/xs/xsbug.md
> +`trace`を使用する際に、コンソール/ログペインで出力を行ごとにカラー化することができます。行の始めにタグを使用します。利用可能なタグは以下の通りです：
```suggestion
`trace`を使用する際に、コンソール/ログペインで出力を行ごとに色付けすることができます。行の始めにタグを使用します。利用可能なタグは以下の通りです：
```

2024-05-15 12:51 UTC, stc1988 commented
@meganetaaan 
確認いただいた点について取り込みを行いました

2024-05-21 12:30 UTC, meganetaaan approved these changes
LGTMです！

2024-05-21 12:30 UTC, merged