Ecma419関連のドキュメントを翻訳
Moddable-OpenSource/moddable-jp pull request #18
Opened 2024-05-14 14:43 UTC by meganetaaan

下記のドキュメントを翻訳します。

@stc1988 レビューをお願いできますでしょうか？

- /documentation/io/io.md
-  /modules/io/readme.md
-  /examples/io/readme.md
-  /examples/io/tcp/readme.md
-  /examples/io/streams/readme.md

念のための補足として、 `/documentation/io/io.md` はEcma-419が勧告される **前に** 作られた、いわばドラフト文書です。 Ecma-419の正式版と食い違いを含む可能性がありますが、今回はリポジトリにあるドラフト文書に則って翻訳しました。

2024-05-14 16:19 UTC, stc1988 commented on examples/io/readme.md
examples以下のアプリケーションを私の方の翻訳ではサンプルで統一してました。コードを例示するときに「例」と訳する

どちらかに統一しましょうか

2024-05-14 16:38 UTC, stc1988 commented
文章量の大きい`io.md`以外についてコメントおよび軽微指摘をしましたので、ご確認をお願いします

2024-05-16 14:06 UTC, stc1988 requested changes
残も確認しました。
言い回し周りの軽微なものとなります

2024-05-16 14:06 UTC, stc1988 commented on examples/io/streams/readme.md
> +この例は、Moddableの [IOボタンの例](https://github.com/Moddable-OpenSource/moddable/tree/public/examples/io/digital/button) を再訪します。ボタンの状態に基づいてLEDをオンおよびオフにします。
実装のやり直しの意の表現がよいかと思います

```suggestion
この例は、Moddableの [IOボタンの例](https://github.com/Moddable-OpenSource/moddable/tree/public/examples/io/digital/button) を再検討します。ボタンの状態に基づいてLEDをオンおよびオフにします。
```

2024-05-16 14:06 UTC, stc1988 commented on examples/io/streams/readme.md
> +LEDの状態が変わるときにコンソール出力はありません。状態の変化を見るためには、LED自体を観察する必要があります。
状態変数の確認としては監視の方が適切な表現になりそうです

```suggestion
LEDの状態が変わるときにコンソール出力はありません。状態の変化を見るためには、LED自体を監視する必要があります。
```

2024-05-16 14:06 UTC, stc1988 commented on examples/io/tcp/readme.md
> +`fetch`、`WebSocket`、および `mqtt` クラスは、組み込み開発者にウェブプラットフォームから馴染みのある、標準的なAPIへのアクセスを提供します。これらは一般的に使用が便利であり、より多くのリソース（RAM、コードサイズ、CPU）を使用します。
意図を汲み取り言い回しを変更しています。

```suggestion
`fetch`、`WebSocket`、および `mqtt` クラスは、組み込み開発者にウェブプラットフォームから馴染みのある、標準的なAPIへのアクセスを提供します。これらは一般的に使いやすいですが、より多くのリソース（RAM、コードサイズ、CPU）を使用します。
```

2024-05-16 14:06 UTC, stc1988 commented on documentation/io/io.md
> +Ecma TC53は、組み込みシステム向けのECMAScriptモジュールを定義するためのチャーターを持つ標準化委員会です。その目標は、リソースが制約された組み込みハードウェア向けのソフトウェアを開発するための標準的なJavaScript APIを定義することです。これは、W3CやWHATWGがウェブ向けのソフトウェアを開発するためのJavaScript APIを定義する作業に類似しています。T
委員会の定義の言い回しを修正しました

```suggestion
Ecma TC53は、組み込みシステム向けのECMAScriptモジュールの標準化を推進するための委員会です。その目標は、リソースが制約された組み込みハードウェア向けのソフトウェアを開発するための標準的なJavaScript APIを定義することです。これは、W3CやWHATWGがウェブ向けのソフトウェアを開発するためのJavaScript APIを定義する作業に類似しています。TC53によって定義されたAPIは、ベンダーに依存せず、したがってホストオペレーティングシステム、CPUアーキテクチャ、およびJavaScriptエンジンに依存しないことを意図しています。IOは、組み込みシステムのほぼすべての用途にとって基本的であるため、TC53によって最初の作業領域として選ばれました。例えば、IOはセンサーと通信の両方をサポートするための前提条件です。
```

2024-05-16 14:06 UTC, stc1988 commented on documentation/io/io.md
> +IOの構成はホストハードウェアに依存します。APIは、ハードウェアの能力に存在する大きな変動に対応する必要があります。例えば、いくつかのハードウェアは、アナログ入力が提供する解像度のビット数を構成することをサポートしています。そのようなホストは、この目的のためにIO構成に`resolution`プロパティを追加するかもしれません。
```suggestion
IOの構成はホストハードウェアに依存します。APIは、ハードウェアの能力に大きな違いがあることを考慮しなければなりません。例えば、いくつかのハードウェアは、アナログ入力が提供する解像度のビット数を構成することをサポートしています。そのようなホストは、この目的のためにIO構成に`resolution`プロパティを追加するかもしれません。
```

2024-05-16 14:06 UTC, stc1988 commented on documentation/io/io.md
> +読み取り操作によって返されるデータは、IOクラスの定義によって異なります。例えば、デジタル入力は0または1の値を持つ数値を返します。
冗長な表現のため数値としています

```suggestion
読み取り操作によって返されるデータは、IOクラスの定義によって異なります。例えば、デジタル入力は0または1の数値を返します。
```

2024-05-16 14:06 UTC, stc1988 commented on documentation/io/io.md
> +書き込み操作で受け入れられるデータは、IOクラスの定義によって異なります。例えば、デジタル出力は0または1の値を持つ数値を期待します。
冗長の表現

```suggestion
書き込み操作で受け入れられるデータは、IOクラスの定義によって異なります。例えば、デジタル出力は0または1の数値を期待します。
```

2024-05-16 14:06 UTC, stc1988 commented on documentation/io/io.md
>  ### Create Operation
他の章も訳しているので、訳とします

```suggestion
### 作成操作
```

2024-05-21 12:31 UTC, meganetaaan commented on examples/io/readme.md
「サンプル」に統一したいですね。修正します。

2024-05-23 03:56 UTC, meganetaaan commented on examples/io/readme.md
「サンプル」に統一しました。
https://github.com/Moddable-OpenSource/moddable-jp/pull/18/commits/039ba78ff0cfb51124a74fc1c982a4869268859c

2024-05-23 03:57 UTC, meganetaaan commented
@stc1988 ひととおり修正しましたのでご確認ください :pray:

2024-05-23 12:56 UTC, stc1988 approved these changes
確認しました。対応ありがとうございます

2024-05-29 15:23 UTC, merged