examples/readme.md　の翻訳
Moddable-OpenSource/moddable-jp pull request #21
Opened 2024-05-22 12:15 UTC by stc1988

@meganetaaan  さんレビューお願いします

2024-05-29 15:36 UTC, meganetaaan requested changes
軽微な指摘1点あります :pray:

2024-05-29 15:36 UTC, meganetaaan commented on examples/readme.md
> +著作権2018-2023 Moddable Tech, Inc.<BR>
"Copyright" は訳さずそのままにしています。

```suggestion
Copyright 2018-2023 Moddable Tech, Inc.<BR>
```

2024-05-31 12:43 UTC, stc1988 commented
@meganetaaan  ご確認ありがとうございます。指摘の点を取り込みました

2024-06-02 12:16 UTC, meganetaaan approved these changes
LGTMです！

2024-06-02 12:16 UTC, merged