documentation/xs/preload.md の翻訳
Moddable-OpenSource/moddable-jp pull request #22
Opened 2024-05-22 15:03 UTC by stc1988

@meganetaaan  さんレビューお願いします

2024-05-29 16:07 UTC, meganetaaan requested changes
軽微な指摘が数点あります :pray:

2024-05-29 16:07 UTC, meganetaaan commented on documentation/xs/preload.md
> +著作権2019-2023 Moddable Tech, Inc.<BR>
"Copyright"は訳さずそのままにしています。

```suggestion
Copyright 2019-2023 Moddable Tech, Inc.<BR>
```

2024-05-29 16:07 UTC, meganetaaan commented on documentation/xs/preload.md
> +プロジェクトのビルドマニフェスト（通常は `manifest.json` という名前のファイル）は、[多くの他のオプション](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/tools/manifest.md)と共に含めるモジュールをリストアップします。マニフェストの任意の部分には、プリロードモジ
```suggestion
プロジェクトのビルドマニフェスト（通常は `manifest.json` という名前のファイル）は、[多くの他のオプション](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/tools/manifest.md)と共にインクルードするモジュールをリストアップします。マニフェストの任意の部分には、プリロードモジュールのリストがあります。
```

2024-05-29 16:07 UTC, meganetaaan commented on documentation/xs/preload.md
> +この例では、`http` ネットワークプロトコルモジュールがプリロードされますが、`main` モジュールプリロードされません。便宜上、Moddable SDKのほとんどの例では `main` モジュールを事前に読プリロードをしていませんが、少し追加作業をすれば可能です。その方法の詳細は以下に記述されています。
```suggestion
この例では、`http` ネットワークプロトコルモジュールがプリロードされますが、`main` モジュールはプリロードされません。便宜上、Moddable SDKのほとんどの例では `main` モジュールをプリロードしていませんが、少し手を加えれば可能です。その方法の詳細は以下に記述されています。
```

2024-05-29 16:07 UTC, meganetaaan commented on documentation/xs/preload.md
> +harden化されたJavaScriptは、`harden()`グローバル関数として再帰的フリーズを形式化します。XSはharden化されたJavaScript（以前のセキュアECMAScript）サポートの一部として`harden()`を実装していますが、現時点ではModdable SDKのビルドには含まれていません。
ここでは"Hardened JavaScript"という、ひとまとまりの用語として使うのが適切なようです。

```suggestion
Hardened JavaScriptでは、`harden()`グローバル関数として再帰的フリーズが正式に提供されています。XSはHardened JavaScript（以前のセキュアECMAScript）サポートの一部として`harden()`を実装していますが、現時点ではModdable SDKのビルドには含まれていません。
```

2024-05-29 16:07 UTC, meganetaaan commented on documentation/xs/preload.md
> +このステップの結果は、[Frozen Realmsの提案](https://github.com/tc39/proposal-frozen-realms)と共通の特徴を持つランタイム環境を生成します。既に説明されたメモリ節約に加えて、スクリプトはJavaScript言語仕様によって定義された組み込みオブジェクトが実行中にランタイムパッチによって変更されないことを知るため、信頼性の高い実行環境を提
```suggestion
このステップの結果は、[Frozen Realmsのプロポーザル](https://github.com/tc39/proposal-frozen-realms)と共通の特徴を持つランタイム環境を生成します。既に説明されたメモリ節約に加えて、スクリプトはJavaScript言語仕様によって定義された組み込みオブジェクトが実行中にランタイムパッチによって変更されないことを知るため、信頼性の高い実行環境を提供します。ランタイムオブジェクトのパッチを排除することも、安全な実行環境を提供するのに寄与します。
```

2024-05-31 13:04 UTC, stc1988 commented
@meganetaaan ご確認ありごがとうございます。指摘の点について取り込みました

2024-06-02 12:17 UTC, meganetaaan approved these changes
LGTMです！

2024-06-02 12:17 UTC, merged