documentaion/commodetto/translate Creating fonts for Moddable applications.md の翻訳
Moddable-OpenSource/moddable-jp pull request #23
Opened 2024-05-25 00:53 UTC by stc1988

@meganetaaan  さんレビューお願いします

2024-06-02 12:46 UTC, meganetaaan requested changes
軽微な表現の指摘が数件あります :pray:

2024-06-02 12:46 UTC, meganetaaan commented on documentation/commodetto/Creating fonts for Moddable applications.md
> +BMFontバイナリ形式で。pngグリフと。fntフォントメトリクスファイルをエクスポートします。
```suggestion
BMFontバイナリ形式で.pngグリフと.fntフォントメトリクスファイルをエクスポートします。
```

2024-06-02 12:46 UTC, meganetaaan commented on documentation/commodetto/Creating fonts for Moddable applications.md
> +fontbmを使用するには、まずシステムにインストールする必要があります。Windowsユーザー向けには、[ダウンロード可能なバイナリ](https://github.com/vladimirgamalyan/fontbm/releases/latest)が用意されています。[macOS](https://github.com/vladimirgamalyan/fontbm#building-m
```suggestion
fontbmを使用するには、まずシステムにインストールする必要があります。Windowsユーザー向けには、[ダウンロード可能なバイナリ](https://github.com/vladimirgamalyan/fontbm/releases/latest)が用意されています。現在[macOS](https://github.com/vladimirgamalyan/fontbm#building-macos)および[Linux](https://github.com/vladimirgamalyan/fontbm#building-linux)ユーザーは、手順に従ってソースコードからビルドする必要があります。
```

2024-06-02 12:46 UTC, meganetaaan commented on documentation/commodetto/Creating fonts for Moddable applications.md
> +fontbmを入手したら、コマンドラインから使用して、Moddable SDKにフォントを追加するために必要な。fntファイルと。pngファイルを生成できます。
```suggestion
fontbmを入手したら、コマンドラインから使用して、Moddable SDKにフォントを追加するために必要な.fntファイルと.pngファイルを生成できます。
```

2024-06-02 12:46 UTC, meganetaaan commented on documentation/commodetto/Creating fonts for Moddable applications.md
> +デフォルトでは、変換プロセスによって出力されるフォントには、Unicode文字の32から127（含む）が含まれます。この動作を上書きするプロパティが4つあります：`characters`、`characterFiles`、`blocks`、および `localization`。これらのプロパティが複数存在する場合、それらが選択するすべての文字が含まれます。
ここは多分「127を含む」という意味で（inclusive）と書いてありますが、日本語だと（inclusive）無くても意味が通りますね。

```suggestion
デフォルトでは、変換プロセスによって出力されるフォントには、Unicode文字の32から127までが含まれます。この動作を上書きするプロパティが4つあります：`characters`、`characterFiles`、`blocks`、および `localization`。これらのプロパティが複数存在する場合、それらが選択するすべての文字が含まれます。
```

2024-06-07 07:27 UTC, stc1988 commented
@meganetaaan ご確認ありがとうございます。ご指摘について取り込みました

2024-06-12 12:56 UTC, meganetaaan approved these changes
LGTMです！

2024-06-12 12:56 UTC, merged