documentaion/devicesの翻訳 esp32, esp8266, pico, nrf52, wasm
Moddable-OpenSource/moddable-jp pull request #24
Opened 2024-06-02 10:50 UTC by stc1988

@meganetaaan さんレビューお願いします。
#3 に含まれてない分もありますが、主要プラットフォームでまとめて対応しました

2024-06-02 12:50 UTC, stc1988 commented
対応ありがとうございます。
ちょうど#24で`esp32.md`を翻訳してしまったところなので取り込み直しますが、本件のアップデート内容としては問題ないです。

2024-06-02 13:02 UTC, stc1988 commented
@meganetaaan 
#25で`esp32.md`が更新されるみたいなので、それが取り込まれた後に差分を取り込み翻訳します。のでレビューはお待ちを

2024-06-10 11:15 UTC, stc1988 commented
@meganetaaan さん、v4.8.0まで差分を取り込みましたので、改めてレビューお願いします

2024-06-27 04:04 UTC, meganetaaan requested changes
軽微な修正提案が数点あります :pray:

2024-06-27 04:04 UTC, meganetaaan commented on documentation/devices/esp32.md
> +- 人気のあるモジュールに4 MBフラッシュ
```suggestion
- 一般的なモジュールには4 MBフラッシュを搭載
```

くらいのニュアンスでいかがでしょうか？

2024-06-27 04:04 UTC, meganetaaan commented on documentation/devices/esp8266.md
> +以下の手順では、コマンドラインツール`mcconfig`を使用してデバイス上で`helloworld`の例を実行することで、セットアップを確認します。
```suggestion
以下の手順では、コマンドラインツール`mcconfig`を使用してデバイス上で`helloworld`のサンプルを実行することで、セットアップを確認します。
```

2024-06-27 04:04 UTC, meganetaaan commented on documentation/devices/esp8266.md
> +# Moddable SDKを使用したESP8266の利用方法
```suggestion
# Moddable SDKでESP8266を使用する
```

タイトルの表現をプラットフォーム間で揃えたいです。

2024-06-27 04:04 UTC, meganetaaan commented on documentation/devices/pico.md
> +> 注: Pico ポートは確かであり、ほぼ完成しています。将来的な作業には以下が含まれる可能性があります:
```suggestion
> 注: Pico への移植は安定していて、ほぼ完了しています。将来的な作業には以下が含まれる可能性があります:
```

2024-06-30 01:24 UTC, stc1988 commented
@meganetaaan  ご確認ありがとうございます。指摘について取り込みました

2024-07-03 11:52 UTC, meganetaaan approved these changes
LGTMです！

2024-07-03 11:52 UTC, merged