modules/data/mp3, commodetto/gif, examples/packages の翻訳
Moddable-OpenSource/moddable-jp pull request #29
Opened 2024-07-03 11:47 UTC by stc1988

@meganetaaan さん、レビューお願いします

2024-07-12 07:28 UTC, meganetaaan requested changes
軽微な指摘があります🙏

2024-07-12 07:28 UTC, meganetaaan commented on examples/packages/readme.md
> +これは、`mcpack` を使用して [mod](https://www.moddable.com/documentation/xs/mods) をビルドおよび実行するサンプルです。`mcrun` を使用します。このサンプルを実行する前に、modのホストをインストールするために `run-mod` 例を実行する必要があります。
```suggestion
これは、`mcpack` を使用して [mod](https://www.moddable.com/documentation/xs/mods) をビルドおよび実行するサンプルです。`mcrun` を使用します。このサンプルを実行する前に、modのホストをインストールするために `run-mod` サンプルを実行する必要があります。
```

2024-07-14 12:46 UTC, stc1988 commented
ご確認ありがとうございます。指摘修正しました

2024-07-14 13:07 UTC, meganetaaan approved these changes
OKです！

2024-07-14 13:08 UTC, merged