translate device/moddable-*
Moddable-OpenSource/moddable-jp pull request #33
Opened 2024-07-19 14:50 UTC by stc1988

@meganetaaan  以下の翻訳になります。レビューお願いします

* /documentation/devices/moddable-two.md
* /documentation/devices/moddable-one.md
* /documentation/devices/moddable-three.md
* /documentation/devices/moddable-display.md
* /documentation/devices/moddable-zero.md
* /documentation/devices/moddable-four.md

2024-07-19 22:55 UTC, phoddie commented
Great work. But you may have [missed one](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/moddable-six.md). ;)

2024-07-20 03:05 UTC, stc1988 commented
@phoddie 
Great news! I just created a merge request for the latest release(#34), so I'll work on it afterward.

2024-07-28 14:12 UTC, meganetaaan requested changes
軽微な修正とコメントがあります :pray:

2024-07-28 14:12 UTC, meganetaaan commented on documentation/devices/moddable-display.md
> +- [Moddable Displaについて](#about-moddable-display)
```suggestion
- [Moddable Displayについて](#about-moddable-display)
```

2024-07-28 14:12 UTC, meganetaaan commented on documentation/devices/moddable-display.md
> +## Moddable Displaについて
```suggestion
## Moddable Displayについて
```

2024-07-28 14:12 UTC, meganetaaan commented on documentation/devices/moddable-four.md
> +		cd $MODDABLE/examples/piu/balls
余分なtabが挿入されているようです。

2024-07-28 14:12 UTC, meganetaaan commented on documentation/devices/moddable-one.md
> +```text
こちらは元文書で余分なtabが翻訳後は消えていますね。少し悩ましいですがインデントの誤りは翻訳時に直してしまい、余力があれば元文書で修正のPRを出す運用としたいです。

2024-07-29 13:50 UTC, stc1988 commented on documentation/devices/moddable-one.md
> +```text
https://github.com/Moddable-OpenSource/moddable/pull/1378

修正このままとしこちら同様にどこかで見直します

2024-07-29 13:53 UTC, stc1988 commented
@meganetaaan 確認ありがとうございます。指摘対応しました

2024-08-05 13:07 UTC, meganetaaan approved these changes
LGTMです！

2024-08-05 13:07 UTC, merged