documentation/commodetto/poco.mdの翻訳
Moddable-OpenSource/moddable-jp pull request #35
Opened 2024-07-24 20:34 UTC by tenugui-taro

@meganetaaan さん
documentation/commodetto/poco.mdを翻訳しました。
翻訳内容についてご確認いただき、フィードバックを頂けますと幸いです。

また、英語ドキュメントでいくつかtypoがありました。
見つけたものはプルリクで修正を出していて、今回の翻訳にも反映しています。

- https://github.com/Moddable-OpenSource/moddable/pull/1375
- https://github.com/Moddable-OpenSource/moddable/pull/1379

どうぞよろしくお願いいたします。

2024-08-05 14:59 UTC, meganetaaan requested changes
コントリビュートありがとうございます！軽微な修正提案がありますのでご確認ください :pray:

2024-08-05 14:59 UTC, meganetaaan commented on documentation/commodetto/poco.md
> +* [例](#examples)
サンプルコードを示すexampleは「サンプル」と呼び方を統一しています。

```suggestion
* [サンプル](#examples)
```

2024-08-05 14:59 UTC, meganetaaan commented on documentation/commodetto/poco.md
> +`PocoPixel`は整数値です。Commodettoで使用される場合、`CommodettoPixel`としてエイリアスされています。詳細については、[Commodettoドキュメント](./commodetto.md)の	`CommodettoPixel`の説明を参照してください。
```suggestion
`PocoPixel`は整数値です。Commodettoで使用される場合、`CommodettoPixel`としてエイリアスされています。詳細については、[Commodettoドキュメント](./commodetto.md)の`CommodettoPixel`の説明を参照してください。
```

2024-08-05 14:59 UTC, meganetaaan commented on documentation/commodetto/poco.md
> +* [例](#examples)
この文書内で他にも該当する箇所が何点かあるので、同様に修正をお願いします。

2024-08-06 08:48 UTC, tenugui-taro reviewed
@meganetaaan さん
お忙しい中、丁寧にレビューいただきありがとうございます！

コメントいただいた2点の修正を行いました。
お手数ですが再度ご確認いただけますと幸いです、よろしくお願いいたします。

2024-08-06 08:48 UTC, tenugui-taro commented on documentation/commodetto/poco.md
> +* [例](#examples)
[f8a51e0](https://github.com/Moddable-OpenSource/moddable-jp/pull/35/commits/f8a51e0e033da0ee4fadde582440fb3f06c09088)にて、まとめて修正を行いました。

※ 原文で「e.g.」と記載されている箇所は「例：」としています。こちらも修正必要であればご連絡ください！

2024-08-06 08:48 UTC, tenugui-taro commented on documentation/commodetto/poco.md
> +`PocoPixel`は整数値です。Commodettoで使用される場合、`CommodettoPixel`としてエイリアスされています。詳細については、[Commodettoドキュメント](./commodetto.md)の	`CommodettoPixel`の説明を参照してください。
見逃していました、ありがとうございます！
[6d0f233](https://github.com/Moddable-OpenSource/moddable-jp/pull/35/commits/6d0f233cbd18250dd127ff880857f123afa00cd1)にて、修正しました。

2024-08-07 13:06 UTC, meganetaaan approved these changes
修正確認しました。LGTMです！

2024-08-07 13:07 UTC, merged

2024-08-07 13:33 UTC, tenugui-taro commented
ご確認いただきありがとうございました！