documentation/displays　の翻訳
Moddable-OpenSource/moddable-jp pull request #36
Opened 2024-07-28 13:21 UTC by stc1988

@meganetaaan さん、レビューお願いします

2024-08-07 14:14 UTC, meganetaaan requested changes
軽微な指摘あります🙏

2024-08-07 14:14 UTC, meganetaaan commented on documentation/displays/readme.md
> +- 配線をテストするための例のアプリを実行するビルドコマンド
```suggestion
- 配線をテストするためのサンプルアプリを実行するビルドコマンド
```

2024-08-07 14:14 UTC, meganetaaan commented on documentation/displays/wiring-guide-adafruit-1.8-st7735.md
> +| **入手可能性** | [Adafruit 1.8" カラー TFT LCD ディスプレイ](https://www.adafruit.com/product/358)<BR>[HiLetgo 1.8" ST7735R](https://www.amazon.com/gp/product/B00LSG51MM/)
```suggestion
| **入手先** | [Adafruit 1.8" カラー TFT LCD ディスプレイ](https://www.adafruit.com/product/358)<BR>[HiLetgo 1.8" ST7735R](https://www.amazon.com/gp/product/B00LSG51MM/)
```

2024-08-07 14:14 UTC, meganetaaan commented on documentation/displays/wiring-guide-adafruit-1.8-st7735.md
> +| **入手可能性** | [Adafruit 1.8" カラー TFT LCD ディスプレイ](https://www.adafruit.com/product/358)<BR>[HiLetgo 1.8" ST7735R](https://www.amazon.com/gp/product/B00LSG51MM/)
他の該当箇所も同様です🙏

2024-08-07 14:14 UTC, meganetaaan commented on documentation/displays/wiring-guide-dotstar.md
> +| Dotstar Display | ESP8266 | ESP8266 Devboardラベル |
```suggestion
| Dotstar Display | ESP8266 | ESP8266 開発ボードラベル |
```

訳を統一

2024-08-08 13:26 UTC, stc1988 commented
@meganetaaan さんご確認ありがとうございます。指摘対応しました

2024-08-08 13:29 UTC, meganetaaan approved these changes
LGTMです🙆

2024-08-08 13:29 UTC, merged