documentation/devices/moddable-six　の翻訳
Moddable-OpenSource/moddable-jp pull request #37
Opened 2024-07-31 14:03 UTC by stc1988

@meganetaaan さん、レビューお願いします

2024-08-05 15:15 UTC, meganetaaan requested changes
軽微な指摘あります :pray:

レビューしてたらModdable Six欲しくなってきましたね！

2024-08-05 15:15 UTC, meganetaaan commented on documentation/devices/moddable-six.md
> +#### 増幅スピーカー
```suggestion
#### アンプ付きスピーカー
```

2024-08-05 15:15 UTC, meganetaaan commented on documentation/devices/moddable-six.md
> +#### 増幅スピーカー
他の該当箇所も修正をお願いします :pray:

2024-08-05 23:27 UTC, stc1988 commented
確認ありがとうございます。指摘対応しました。

> レビューしてたらModdable Six欲しくなってきましたね！
そうですよね。私は耐えきれず注文してしまいました 👍

2024-08-07 13:19 UTC, meganetaaan reviewed
追加の指摘１件あります🙋

2024-08-07 13:19 UTC, meganetaaan commented on documentation/devices/moddable-six.md
> +	- [ティアリング効果](#tearing-effect)
- [Amplified Audio](#amplified-audio)
の訳が消えています。
（ここもアンプ付きオーディオとかですかね？）

2024-08-08 13:40 UTC, stc1988 commented
すみません、訳そうか試行錯誤中のままコミットしていました。
修正しましたので、ご確認ください 🙇

2024-08-09 20:49 UTC, meganetaaan approved these changes
LGTMです！🙆

2024-08-09 20:49 UTC, merged