translate examples/pins/audioout/http-stream/readme.md
Moddable-OpenSource/moddable-jp pull request #40
Opened 2024-08-10 13:09 UTC by stc1988

@meganetaaan  さん、レビューお願いします

2024-08-12 14:25 UTC, meganetaaan requested changes
軽微な修正1点あります🙏

2024-08-12 14:25 UTC, meganetaaan commented on examples/pins/audioout/http-stream/readme.md
> +SBCオーディオファイルは、ヘッダーや追加のフレーミングなしでSBCオーディオフレームのシーケンスです。次のコマンドラインは、任意のHTTPサーバーから配信できるSBCオーディオファイルを生成するためにffmpegを使用します。
```suggestion
SBCオーディオファイルは、ヘッダーや追加のフレームの無い、SBCオーディオフレームの系列です。次のコマンドラインは、任意のHTTPサーバーから配信できるSBCオーディオファイルを生成するためにffmpegを使用します。
```
違和感のある文章を修正

2024-08-12 15:51 UTC, stc1988 commented
@meganetaaan さん、ご確認ありがとうございます。指摘について取り込みしました

2024-08-13 04:21 UTC, meganetaaan approved these changes
LGTMです🙆

2024-08-13 04:21 UTC, merged