documentation/drivers/neostrand/neostrand.md の翻訳
Moddable-OpenSource/moddable-jp pull request #41
Opened 2024-08-13 12:53 UTC by stc1988

@meganetaaan さん、レビューお願いします

2024-08-13 15:05 UTC, meganetaaan requested changes
軽微な表現の指摘あります🙏

2024-08-13 15:05 UTC, meganetaaan commented on documentation/drivers/neostrand/neostrand.md
> +fade | 0.2 | [0..1] | テールがどれだけ早くフェードするか
```suggestion
fade | 0.2 | [0..1] | 末尾がどれだけ早くフェードするか
```

2024-08-13 15:05 UTC, meganetaaan commented on documentation/drivers/neostrand/neostrand.md
> +[ビルドインのエフェクトの一覧](#builtin) はこのドキュメントの後に出てきます。
```suggestion
[ビルトインのエフェクトの一覧](#builtin) はこのドキュメントの後に出てきます。
```

2024-08-13 15:05 UTC, meganetaaan commented on documentation/drivers/neostrand/neostrand.md
> +| パラメータ | デフォルト | 範囲 | 説明 |
```suggestion
| パラメータ | デフォルト値 | 範囲 | 説明 |
```

2024-08-13 15:05 UTC, meganetaaan commented on documentation/drivers/neostrand/neostrand.md
> +| パラメータ | デフォルト | 範囲 | 説明 |
```suggestion
| パラメータ | デフォルト値 | 範囲 | 説明 |
```

2024-08-13 15:05 UTC, meganetaaan commented on documentation/drivers/neostrand/neostrand.md
> +| パラメータ | デフォルト | 範囲 | 説明 |
```suggestion
| パラメータ | デフォルト値 | 範囲 | 説明 |
```

2024-08-13 15:05 UTC, meganetaaan commented on documentation/drivers/neostrand/neostrand.md
> +| パラメータ | デフォルト | 範囲 | 説明 |
他の該当箇所も修正おねがいします🙏

2024-08-13 15:05 UTC, meganetaaan commented on documentation/drivers/neostrand/neostrand.md
> +fade | 0.2 | [0..1] | テールがどれだけ早くフェードするか
```suggestion
fade | 0.2 | [0..1] | 末尾がどれだけ早くフェードするか
```

2024-08-13 15:05 UTC, meganetaaan commented on documentation/drivers/neostrand/neostrand.md
> +duration | 1000 | | フルブライトネスのピクセルをオフにする時間（ミリ秒）
```suggestion
duration | 1000 | | 明るさ最大のピクセルをオフにするまでの時間（ミリ秒）
```

2024-08-14 03:20 UTC, stc1988 commented
@meganetaaan ご確認ありがとうざいます。指摘修正しました

2024-08-14 04:19 UTC, meganetaaan approved these changes
LGTMです🙆

2024-08-14 04:19 UTC, merged