documentation/files/files.md の翻訳
Moddable-OpenSource/moddable-jp pull request #42
Opened 2024-08-16 14:20 UTC by stc1988

@meganetaaan さん、レビューお願いします

2024-08-19 11:08 UTC, meganetaaan requested changes
軽微な指摘あります🙏

2024-08-19 11:08 UTC, meganetaaan commented on documentation/files/files.md
> +ファイルモジュールには、ファイルおよびサポートされている場合はディレクトリにアクセスするために使用されるいくつかのクラスが含まれています。
```suggestion
ファイルモジュールには、ファイルおよび（サポートされている場合は）ディレクトリにアクセスするために使用されるいくつかのクラスが含まれています。
```

2024-08-19 11:08 UTC, meganetaaan commented on documentation/files/files.md
> +スラッシュ文字 (`/`) は、ネイティブで異なるパスセパレータを使用するホストでも、常にパスセパレータとして使用されます。
```suggestion
スラッシュ文字 (`/`) は、ネイティブで異なるパスの区切り文字を使用するホストでも、常にパスの区切り文字として使用されます。
```

2024-08-19 15:23 UTC, stc1988 commented
@meganetaaan さん確認ありがとうございます。指摘の点について取り込みました

2024-08-20 15:24 UTC, meganetaaan approved these changes
LGTMです！

2024-08-20 15:24 UTC, merged