documentation/commodetto/outline/Outlines.mdの翻訳
Moddable-OpenSource/moddable-jp pull request #43
Opened 2024-08-17 14:35 UTC by tenugui-taro

@meganetaaan さん
documentation/commodetto/outline/Outlines.mdを翻訳しました。
翻訳内容についてご確認いただき、フィードバックを頂けますと幸いです。

※ 「Example using Poco」-> 「Pocoを使用した例」としています。
「Pocoを使用したサンプル」としていないのは、この章で出てくるオシロスコープで「サンプル」の用語が使われているためです。

どうぞよろしくお願いいたします。

2024-08-20 15:23 UTC, meganetaaan requested changes
1点だけ軽微な表現の修正提案があります🙏
この文書では確かに「example=例」とするほうが、混同が避けられて適切ですね。

2024-08-20 15:23 UTC, meganetaaan commented on documentation/commodetto/outline/Outlines.md
> +図形を定義するために、親しみのあるプログラミングインターフェースがサポートされています：
```suggestion
図形を定義するために、馴染みのあるプログラミングインターフェースがサポートされています：
```

2024-08-26 09:59 UTC, tenugui-taro commented
@meganetaaan さん
レビューいただきありがとうございます！
対応遅くなり申し訳ありません、提案いただいた箇所反映させていただきました！

2024-08-26 13:26 UTC, meganetaaan approved these changes
修正ありがとうございます。LGTMです🙆

2024-08-26 13:26 UTC, merged