examples/drivers の翻訳
Moddable-OpenSource/moddable-jp pull request #45
Opened 2024-08-19 10:56 UTC by stc1988

@meganetaaan さん、レビューお願いします

2024-08-23 15:49 UTC, meganetaaan requested changes
1点軽微な表現の指摘あります🙏

2024-08-23 15:49 UTC, meganetaaan commented on examples/drivers/readme.md
> +[Commodetto](../../documentation/commodetto/commodetto.md)アプリは、[M5Stack Fire](https://www.aliexpress.com/item/32847906756.html?spm=2114.12010615.8148356.14.11c127aeBNzJBb)用です。オンボードのInvenSense MPU-605
```suggestion
[M5Stack Fire](https://www.aliexpress.com/item/32847906756.html?spm=2114.12010615.8148356.14.11c127aeBNzJBb)用の[Commodetto](../../documentation/commodetto/commodetto.md)アプリです。オンボードのInvenSense MPU-6050加速度計/ジャイロとXtrinsic MAG3110磁力計のデータに基づいてデバイスの動きを視覚化します。
```

2024-08-24 01:58 UTC, stc1988 commented
@meganetaaan さん、ご確認ありがとうございます。指摘取り込みました

2024-08-24 02:00 UTC, meganetaaan approved these changes
LGTMです🙆

2024-08-24 02:00 UTC, merged