examples/commodettoおよびexamples/js/compartmentsの翻訳
Moddable-OpenSource/moddable-jp pull request #46
Opened 2024-08-23 14:10 UTC by stc1988

@meganetaaan さん、レビューお願いします

2024-08-30 14:54 UTC, meganetaaan requested changes

2024-08-30 14:54 UTC, meganetaaan commented on examples/commodetto/readme.md
> +`static`のサンプルは、Pocoを使用して効率的に静的をレンダリングする方法を示しています。
「静的をレンダリング」という表現に違和感があります。staticのAPIを今回初めて知ったのですが、何をするものなんでしょうか？  Commodettoのドキュメントにも載っていない気がする

2024-08-30 14:55 UTC, meganetaaan commented
1箇所指摘&質問があります🙏

2024-08-31 14:50 UTC, stc1988 commented on examples/commodetto/readme.md
> +`static`のサンプルは、Pocoを使用して効率的に静的をレンダリングする方法を示しています。
サクッと読み飛ばしていました。確かにどこにも載っていないし、効率的にレンダリングできる機能なら使ってみたい気持ちもあるのでModdable側で聞いてみますね。

2024-08-31 14:57 UTC, stc1988 commented on examples/commodetto/readme.md
> +`static`のサンプルは、Pocoを使用して効率的に静的をレンダリングする方法を示しています。
https://github.com/Moddable-OpenSource/moddable/issues/1396 で質問しました。

2024-09-01 14:05 UTC, meganetaaan commented on examples/commodetto/readme.md
> +`static`のサンプルは、Pocoを使用して効率的に静的をレンダリングする方法を示しています。
質問ありがとうございます！回答来てましたね。
なるほどテレビの砂嵐のことをstaticって呼ぶんですね〜
https://ameblo.jp/english-teacher-yohei/entry-12428673445.html

そしたら「"static（テレビの砂嵐）"」みたいに注釈をつけるのはどうでしょうか。
（これだけだとまだ用途がよくわからないので、本家側でユースケースの説明も足してもらえたらいいですね。）

2024-09-01 14:25 UTC, stc1988 commented on examples/commodetto/readme.md
> +`static`のサンプルは、Pocoを使用して効率的に静的をレンダリングする方法を示しています。
補足ありがとうございます。確かにstatic=砂嵐のようですね。

> * Show static when waiting for video to be available
> * Demonstrate how to implement and integrate a custom renderer extension for Poco
> * Confirm that irregular shaped objects, such as animated GIFs, are not drawing the background pixels

砂嵐の理解で読み直すと、1,3は砂嵐を描画することの使い道の事例で、2は今回のstaticみたいなPocoを拡張できる事例だと言ってる気がしますね。

Module側に実装があるのでフレームワークの描画機能のように思ってましたが、Pocoの拡張で高速に砂嵐を描画できるよ、と理解しました。

2024-09-01 15:14 UTC, meganetaaan approved these changes
LGTMです🙆

2024-09-01 15:14 UTC, merged