modules/driversの翻訳
Moddable-OpenSource/moddable-jp pull request #48
Opened 2024-09-04 12:34 UTC by stc1988

@meganetaaan さん、レビューお願いします

2024-09-06 12:20 UTC, meganetaaan requested changes
軽微な指摘あります。
何箇所かURLが翻訳されていますのでご確認ください🙏

2024-09-06 12:20 UTC, meganetaaan commented on modules/drivers/readme.md
> +* **Functions** - 部品の公開された機能/測定
```suggestion
* **Functions** - 部品の公開された機能/測定項目
```

2024-09-06 12:20 UTC, meganetaaan commented on modules/drivers/readme.md
> +* **ECMA-419** - [ECMA-419](https://www.ecma-international.org/publications-and-standards/standards/ecma-419/) 標準準拠:
```suggestion
* **ECMA-419** - [ECMA-419](https://www.ecma-international.org/publications-and-standards/standards/ecma-419/) 標準準拠状況:
```

2024-09-06 12:20 UTC, meganetaaan commented on modules/drivers/readme.md
> +| AM2320                     | Aosong Electronic        | 湿度、 温度                  | Yes          | [Link](https://cdn-learn.adafruit.com/downloads/pdf/adafruit-am2320-温度-湿度-i2c-sensor.pdf)
URLが訳されています

2024-09-06 12:20 UTC, meganetaaan commented on modules/drivers/readme.md
> +| GDEW0154M09                | DALIAN GOOD DISPLAY      | ディスプレイ                                |              | [Link](https://www.good-display.com/comp/xcompanyFile/downloadNew.do?appId=24&fid=333&
URLが訳されています

2024-09-06 12:20 UTC, meganetaaan commented on modules/drivers/readme.md
> +| HC-SR04                    | SparkFun                 | 超音波距離                    | Yes          | [Link](https://cdn.sparkfun.com/datasheets/Sensors/近接距離/HCSR04.pdf)
URLが訳されています

2024-09-06 12:20 UTC, meganetaaan commented on modules/drivers/sensors/ft6206/readme.md
> +プロジェクトで同期実装を使用するには、このディレクトリの`manifest.json`を含めます。非同期実装を使用するには、`manifest_async.json`を含めます。
```suggestion
プロジェクトで同期実装を使用するには、このディレクトリの`manifest.json`をインクルードします。非同期実装を使用するには、`manifest_async.json`をインクルードします。
```

2024-09-07 10:45 UTC, stc1988 commented
ご確認ありがとうございます。指摘の点について見直しました。

2024-09-07 13:14 UTC, meganetaaan approved these changes
修正ありがとうございます。LGTMです！

2024-09-07 13:14 UTC, merged