documentation/drivers の翻訳
Moddable-OpenSource/moddable-jp pull request #50
Opened 2024-09-16 03:17 UTC by stc1988

@meganetaaan さん、レビューお願いします

2024-09-17 14:48 UTC, meganetaaan requested changes
軽微な指摘あります🙏

2024-09-17 14:48 UTC, meganetaaan commented on documentation/drivers/MCP230XX/MCP230XX.md
> +| `hz`       | `number` | 100kHz | I2Cデバイスのクロックスピード。 |
どちらかというとクロック周波数のほうがメジャーな呼称です。

```suggestion
| `hz`       | `number` | 100kHz | I2Cデバイスのクロック周波数。 |
```

2024-09-17 16:08 UTC, stc1988 commented
@meganetaaan さん、ご確認ありがとうございます。
指摘取り込みと最新コミット取り込みのマージコンフリクト解消済みです

2024-09-24 15:48 UTC, meganetaaan commented
ごめんなさい、見逃していましたが、クロックスピードが複数箇所あるのでそちらも直していただけると嬉しいです 🙏

2024-09-25 12:18 UTC, stc1988 commented
@meganetaaan ご確認ありがとうございます。grepして残１箇所のはずですが、修正しました

2024-09-25 12:58 UTC, meganetaaan approved these changes

2024-09-25 12:59 UTC, meganetaaan commented
LGTMです！ありがとうございます🙏

2024-09-25 12:59 UTC, merged