Documentation/piuの翻訳
Moddable-OpenSource/moddable-jp pull request #52
Opened 2024-09-30 12:47 UTC by ronron-gh

/documentation/piu/piu.mdの翻訳です。レビューをお願いいたします。（CLAは提出し承認いただきました。）

2024-10-15 14:49 UTC, meganetaaan requested changes
ありがとうございます！
力作ですね…！量が多いので何回かに分けてレビューできればと思います。まずは1000行付近まで見ました。よろしくおねがいします。

2024-10-15 14:49 UTC, meganetaaan commented on documentation/piu/piu.md
> +    * [包含階層と外観](#包含階層と外観)
「包含階層」と直訳するより「コンテンツ階層」と少し意訳したほうが伝わりそうです。

```suggestion
    * [コンテンツ階層と外観](#コンテンツ階層と外観)
```

2024-10-15 14:49 UTC, meganetaaan commented on documentation/piu/piu.md
> +包含階層にアタッチされていないcontentsは*unbound* contentsと呼ばれ、包含階層にアタッチされているcontentsは*bound* contentsと呼ばれます。包含階層の一部であるオブジェクトのみが画面に表示されます。
```suggestion
包含階層にアタッチされていないコンテンツは*unbound* コンテンツと呼ばれ、包含階層にアタッチされているコンテンツは*bound* コンテンツと呼ばれます。包含階層の一部であるオブジェクトのみが画面に表示されます。

```

2024-10-15 14:49 UTC, meganetaaan commented on documentation/piu/piu.md
> +unbound contentsはレイアウトには参加しません。測定も調整も行われないため、位置とサイズは「未定義」となり、変更できません。
```suggestion
unbound コンテンツはレイアウトには参加しません。測定も調整も行われないため、位置とサイズは「未定義」となり、変更できません。

```

2024-10-15 14:49 UTC, meganetaaan commented on documentation/piu/piu.md
> +| `anonymous` | `function` | 結果が作成するインスタンスを初期化するためのプロパティを持つオブジェクトを返す関数
```suggestion
| `anonymous` | `function` | 生成されるインスタンスを初期化するためのプロパティを持つオブジェクトを返す関数

```

2024-10-15 14:49 UTC, meganetaaan commented on documentation/piu/piu.md
> +
Behaviorをどう訳すか悩ましいですね。
「動作」だと物理的な動きのイメージが強いので「振る舞い」または単に「ビヘイビア」と訳すのが良いかもしれません。

2024-10-15 14:49 UTC, meganetaaan commented on documentation/piu/piu.md
> +`container` オブジェクトは、他の `content` オブジェクトを含むことができる `content` オブジェクトです。コンテナでは、`content` オブジェクトは二重リンク リストに格納されます。`content` オブジェクトには、`content` プロパティを使用してインデックスまたは名前でアクセスすることもできます (例: `container.content(0)
```suggestion
`container` オブジェクトは、他の `content` オブジェクトを含むことができる `content` オブジェクトです。コンテナでは、`content` オブジェクトは双方向連結リストに格納されます。`content` オブジェクトには、`content` プロパティを使用してインデックスまたは名前でアクセスすることもできます (例: `container.content(0)` または `container.content("foo")`)。

```

2024-10-15 14:49 UTC, meganetaaan commented on documentation/piu/piu.md
> +`content` オブジェクトの場合と同じです ([コンテンツ オブジェクト](#content-object) セクションの [辞書](#content-dictionary) を参照)。さらに次のようになります。
```suggestion
`content` オブジェクトの場合と同じです ([コンテンツ オブジェクト](#content-object) セクションの [辞書](#content-dictionary) を参照)。さらに次のプロパティを含みます。

```

2024-10-20 14:34 UTC, ronron-gh commented on documentation/piu/piu.md
> +    * [包含階層と外観](#包含階層と外観)
確かに「コンテンツ階層」だとわかりやすいですね。全体的に「包含階層」を「コンテンツ階層」に修正しました。

2024-10-20 14:35 UTC, ronron-gh commented on documentation/piu/piu.md
> +包含階層にアタッチされていないcontentsは*unbound* contentsと呼ばれ、包含階層にアタッチされているcontentsは*bound* contentsと呼ばれます。包含階層の一部であるオブジェクトのみが画面に表示されます。
全体的に「content」を「コンテンツ」に修正しました。

2024-10-20 14:36 UTC, ronron-gh commented on documentation/piu/piu.md
> +unbound contentsはレイアウトには参加しません。測定も調整も行われないため、位置とサイズは「未定義」となり、変更できません。
全体的に「content」を「コンテンツ」に修正しました。

2024-10-20 14:38 UTC, ronron-gh commented on documentation/piu/piu.md
> +| `anonymous` | `function` | 結果が作成するインスタンスを初期化するためのプロパティを持つオブジェクトを返す関数
全体的に「結果が作成する」を「生成される」に修正しました。

2024-10-20 14:44 UTC, ronron-gh commented on documentation/piu/piu.md
> +
全体的に検索しましたが、behaviorは全て' 'で囲われておりオブジェクト名を指しているように思えるので、behaviorのままでもよいような気がしました。ただし1か所、「Behavior and Flow」という見出しがあったため「振る舞いとフロー」に修正しました。

2024-10-20 14:44 UTC, ronron-gh commented on documentation/piu/piu.md
> +`container` オブジェクトは、他の `content` オブジェクトを含むことができる `content` オブジェクトです。コンテナでは、`content` オブジェクトは二重リンク リストに格納されます。`content` オブジェクトには、`content` プロパティを使用してインデックスまたは名前でアクセスすることもできます (例: `container.content(0)
修正しました。

2024-10-20 14:45 UTC, ronron-gh commented on documentation/piu/piu.md
> +`content` オブジェクトの場合と同じです ([コンテンツ オブジェクト](#content-object) セクションの [辞書](#content-dictionary) を参照)。さらに次のようになります。
全体的に検索して修正しました。

2024-10-23 14:46 UTC, meganetaaan requested changes
最後までレビューしました！
軽微な言い回しや語句の指摘が数点あります :pray:

2024-10-23 14:46 UTC, meganetaaan commented on documentation/piu/piu.md
> +| `content` | `content` | 追加する `content` オブジェクト。バインドされていない必要があります。つまり、そのコンテナーは `null` である必要があります。
```suggestion
| `content` | `content` | 追加する `content` オブジェクト。バインドされていない必要があります。つまり、そのコンテナは `null` である必要があります。

```

コンテナに統一

2024-10-23 14:46 UTC, meganetaaan commented on documentation/piu/piu.md
> +`Application.prototype` のインスタンスを作成する関数であるコンストラクターを返します。結果の `prototype` プロパティは `Application.prototype` です。結果には `template` 関数も提供されます。
```suggestion
`Application.prototype` のインスタンスを作成する関数であるコンストラクターを返します。戻り値の `prototype` プロパティは `Application.prototype` です。戻り値には `template` 関数も提供されます。

```

関数の実行結果であることが伝わるように「戻り値」と訳しました。

2024-10-23 14:46 UTC, meganetaaan commented on documentation/piu/piu.md
> +| `Behavior` | `function` | `Behavior.prototype` のインスタンスを作成する関数。通常は `Behavior` クラスを拡張するクラスです。このコンテンツは、この `behavior` のインスタンスを作成し、その `behavior` パラメータを作成されたインスタンスに設定し、`onCreate` メソッドをトリガーします。
```suggestion
| `Behavior` | `function` | `Behavior.prototype` のインスタンスを作成する関数。通常は `Behavior` クラスを継承するクラスです。このコンテンツは、この `behavior` のインスタンスを作成し、その `behavior` パラメータを作成されたインスタンスに設定し、`onCreate` メソッドをトリガーします。

```

JavaScriptのextendsは継承を意味しますね。

2024-10-23 14:46 UTC, meganetaaan commented on documentation/piu/piu.md
> +このコンテンツにより、`id` の値で指定されたイベントがトリガーされます。委任されたイベントの最初のパラメータはこのコンテンツです。委任されたイベントの追加パラメータ (存在する場合) は、`delegate` 関数の追加パラメータです。
```suggestion
このコンテンツにより、`id` の値で指定されたイベントがトリガーされます。移譲されたイベントの最初のパラメータはこのコンテンツです。移譲されたイベントの追加パラメータ (存在する場合) は、`delegate` 関数の追加パラメータです。

```

2024-10-23 14:46 UTC, meganetaaan commented on documentation/piu/piu.md
> +このコンテンツの時計を開始します。
```suggestion
このコンテンツのクロックを開始します。

```

「クロック」「時計」を「クロック」に統一

2024-10-28 11:27 UTC, ronron-gh commented on documentation/piu/piu.md
> +| `content` | `content` | 追加する `content` オブジェクト。バインドされていない必要があります。つまり、そのコンテナーは `null` である必要があります。
全体的に修正しました。

2024-10-28 11:28 UTC, ronron-gh commented on documentation/piu/piu.md
> +`Application.prototype` のインスタンスを作成する関数であるコンストラクターを返します。結果の `prototype` プロパティは `Application.prototype` です。結果には `template` 関数も提供されます。
全体的に修正しました。

2024-10-28 11:28 UTC, ronron-gh commented on documentation/piu/piu.md
> +| `Behavior` | `function` | `Behavior.prototype` のインスタンスを作成する関数。通常は `Behavior` クラスを拡張するクラスです。このコンテンツは、この `behavior` のインスタンスを作成し、その `behavior` パラメータを作成されたインスタンスに設定し、`onCreate` メソッドをトリガーします。
修正しました。

2024-10-28 11:28 UTC, ronron-gh commented on documentation/piu/piu.md
> +このコンテンツにより、`id` の値で指定されたイベントがトリガーされます。委任されたイベントの最初のパラメータはこのコンテンツです。委任されたイベントの追加パラメータ (存在する場合) は、`delegate` 関数の追加パラメータです。
全体的に修正しました。

2024-10-28 11:28 UTC, ronron-gh commented on documentation/piu/piu.md
> +このコンテンツの時計を開始します。
全体的に修正しました。

2024-10-28 14:59 UTC, meganetaaan approved these changes
修正ありがとうございました。LGTMです！

2024-10-28 15:00 UTC, merged