network、ethernet、securesocket　の翻訳
Moddable-OpenSource/moddable-jp pull request #56
Opened 2024-12-23 14:25 UTC by stc1988

@meganetaaan  さんレビューお願いします

2024-12-31 14:35 UTC, meganetaaan requested changes
PRありがとうございます！
軽微な表現の指摘が数点あります :pray:

2024-12-31 14:35 UTC, meganetaaan commented on documentation/network/ethernet.md
> +これらのサンプルでイーサネットを使用したい場合は、単に `manifest_net.json` を `manifest_net_ethernet.json` に置き換えるだけです。`manifest_net.json` と `manifest_net_ethernet.json` の両方を含めるべきではないことに注意してください。どちらか一方のみを含めてください。
```suggestion
これらのサンプルでイーサネットを使用したい場合は、単に `manifest_net.json` を `manifest_net_ethernet.json` に置き換えるだけです。`manifest_net.json` と `manifest_net_ethernet.json` の両方をインクルードすべきではないことに注意してください。どちらか一方のみをインクルードしてください。
```

他の翻訳に倣って「マニフェストをインクルードする」という表現を使います

2024-12-31 14:35 UTC, meganetaaan commented on documentation/network/ethernet.md
> +> **注:** アプリケーションは、イーサネット接続接続を開始するために`Ethernet`クラスの静的メソッド`start`を呼び出す必要があります。`start`を呼び出さないと、`Ethernet`コンストラクタに渡されたコールバックは決して呼び出されません。
```suggestion
> **注:** アプリケーションは、イーサネット接続を開始するために`Ethernet`クラスの静的メソッド`start`を呼び出す必要があります。`start`を呼び出さないと、`Ethernet`コンストラクタに渡されたコールバックは決して呼び出されません。
```

2024-12-31 14:35 UTC, meganetaaan commented on documentation/network/ethernet.md
> +次の例は、イーサネット接続への接続プロセスを開始し、接続が成功してイーサネット接続デバイスにIPアドレスが割り当てられたときにコンソールにログ出力します。
```suggestion
次の例は、イーサネットへの接続プロセスを開始し、接続が成功してイーサネットデバイスにIPアドレスが割り当てられたときにコンソールにログ出力します。
```

2024-12-31 14:35 UTC, meganetaaan commented on documentation/network/ethernet.md
> +### 例: イーサネット IPアドレスの取得
```suggestion
### サンプル: イーサネット IPアドレスの取得
```

サンプルコードやプロジェクトを表現するのに「サンプル」という語句を統一して用います。

2024-12-31 14:35 UTC, meganetaaan commented on documentation/network/network.md
> +`MDNS` クラスは [Multicast DNS](https://tools.ietf.org/html/rfc6762) のディスカバリーとサービスを扱うためのサービスを実装します。これには `.local` 名のクレーム（取得）、mDNS サービス利用可能のアドバータイズ（通知）、および利用可能な mDNS サービスのスキャンが含まれます。
```suggestion
`MDNS` クラスは [Multicast DNS](https://tools.ietf.org/html/rfc6762) のディスカバリーとサービスを扱うためのサービスを実装します。これには `.local` 名のクレーム（取得）、mDNS サービス利用可能のアドバタイズ（通知）、および利用可能な mDNS サービスのスキャンが含まれます
```

2024-12-31 14:35 UTC, meganetaaan commented on documentation/network/network.md
> +`add` 関数は、アドバータイズするための mDNS サービス記述を登録します。サービスレコードには次のプロパティが含まれます:
```suggestion
`add` 関数は、アドバタイズするための mDNS サービス記述を登録します。サービスレコードには次のプロパティが含まれます:
```

2024-12-31 14:36 UTC, meganetaaan commented
TLSやWebSocket、MQTTなど、ネットワーク関連の様々なモジュールが公式にサポートされているのは大きなメリットですよね。日本のユーザにも伝わると良いなあ。

2025-01-03 12:29 UTC, stc1988 commented on documentation/network/ethernet.md
> +### 例: イーサネット IPアドレスの取得
`examples`フォルダ以下のサンプルアプリを指す場合は`サンプル`と表記していますが、同ドキュメント内にコード例が例示されている場合は`例`と表記しているいますので本指摘箇所は修正不要と考えています。

2025-01-03 12:36 UTC, stc1988 commented
確認ありがとうございます。指摘修正しました。

基本的なIoT機器向けのネットワーク機能は揃っているので活用例をアピールしていきたいですね

2025-01-06 02:26 UTC, meganetaaan approved these changes
修正ありがとうございます。LGTMです！

2025-01-06 02:27 UTC, merged